# /*
#  * ----------------------------------------------
#  * docker-compose.dev.yml（開發時生效） 
#  * 2025-07-22
#  * ----------------------------------------------
#  */

services:
  web:
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules # 專案目錄模式
      - ./ssl:/app/ssl # 自簽憑證掛載進入容器
    ports:
      - "3000:3000"      
    env_file:
      - .env

  db:
    ports:
        - "5432:5432"