# /*
#  * ----------------------------------------------
#  * docker-compose.dev.yml（開發時生效） 
#  * 2025-07-22
#  * ----------------------------------------------
#  */

services:
  studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: "${UID}:${GID}"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "5555:5555"
    env_file:
      - .env
    command: npx prisma studio --browser none --port 5555
    depends_on:
      - db
    profiles:
      - studio

  web:
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules # 專案目錄模式
      - ./ssl:/app/ssl # 自簽憑證掛載進入容器
    ports:
      - "3000:3000"      
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=6144
